name: Check Format when Fix Format runned

on:
  workflow_run:
    workflows: ["Fix Format"]
    types:
      - completed

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Check format with Prettier
        run: bun run format:check
