name: Check Format

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Check format with Prettier
        run: bun run format:check
