name: Check Format Caller

on:
  pull_request:

permissions:
  actions: write
  contents: read

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Trigger Check Format
        run: gh workflow run check-format.yml --ref ${{ github.event.pull_request.head.ref }} --field sha=${{ github.event.pull_request.head.sha }}
