name: Fix Format

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Fix format with Prettier
        run: bun run format

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix format"

      - name: Trigger Check Format
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: gh workflow run check-format.yml --ref $GITHUB_REF --inputs sha=${{ steps.auto-commit-action.outputs.commit_hash }}
