name: Fix Format

on:
  workflow_run:
    workflows: ["Check Format"]
    types:
      - completed

permissions:
  actions: write
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest
    # Check Formatが失敗した時だけFix Formatを自動実行
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install --frozen-lockfile

      - name: Fix format with Prettier
        run: bun run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: fix format"
